import { db } from "@/db";
import { assets, monthlySeasonality, seasonalWindows, assetTechnicals, seasonalUpdates } from "@/db/schema";
import { eq } from "drizzle-orm";

export interface SeedAssetData {
  ticker: string;
  name: string;
  category: "Indices" | "Sectors" | "Commodities" | "Forex" | "Bonds" | "Crypto";
  sector?: string;
  description: string;
  equityclockUrl: string;
  lastPrice: number;
  dayChangePct: number;
  rsi14: number;
  aboveSma50: boolean;
  aboveSma200: boolean;
  confluenceScore: number;
  monthly: Array<{
    month: number;
    winRate: number;
    avgReturn: number;
    medianReturn: number;
    maxGain: number;
    maxLoss: number;
  }>;
  windows: Array<{
    title: string;
    bias: "bullish" | "bearish" | "neutral";
    startMonth: number;
    startDay: number;
    endMonth: number;
    endDay: number;
    winRate: number;
    avgReturn: number;
    description: string;
  }>;
}

export const SEED_ASSETS: SeedAssetData[] = [
  {
    ticker: "SPX",
    name: "S&P 500 Index",
    category: "Indices",
    sector: "Broad Market",
    description: "Benchmark stock index tracking 500 largest US publicly traded companies.",
    equityclockUrl: "https://equityclock.com/charts/sp-500-index-spx-seasonal-chart/",
    lastPrice: 5120.45,
    dayChangePct: 0.42,
    rsi14: 58.2,
    aboveSma50: true,
    aboveSma200: true,
    confluenceScore: 84,
    monthly: [
      { month: 1, winRate: 60, avgReturn: 1.2, medianReturn: 1.1, maxGain: 6.1, maxLoss: -5.1 },
      { month: 2, winRate: 55, avgReturn: 0.1, medianReturn: 0.3, maxGain: 5.4, maxLoss: -6.2 },
      { month: 3, winRate: 65, avgReturn: 1.4, medianReturn: 1.2, maxGain: 7.0, maxLoss: -4.8 },
      { month: 4, winRate: 72, avgReturn: 1.9, medianReturn: 1.7, maxGain: 8.2, maxLoss: -3.5 },
      { month: 5, winRate: 58, avgReturn: 0.2, medianReturn: 0.4, maxGain: 4.8, maxLoss: -5.9 },
      { month: 6, winRate: 52, avgReturn: 0.1, medianReturn: 0.2, maxGain: 5.1, maxLoss: -4.9 },
      { month: 7, winRate: 68, avgReturn: 1.6, medianReturn: 1.5, maxGain: 6.9, maxLoss: -3.8 },
      { month: 8, winRate: 48, avgReturn: -0.3, medianReturn: -0.1, maxGain: 4.2, maxLoss: -6.5 },
      { month: 9, winRate: 42, avgReturn: -1.1, medianReturn: -0.8, maxGain: 3.5, maxLoss: -8.9 },
      { month: 10, winRate: 62, avgReturn: 1.2, medianReturn: 1.0, maxGain: 8.0, maxLoss: -7.1 },
      { month: 11, winRate: 75, avgReturn: 2.5, medianReturn: 2.3, maxGain: 9.1, maxLoss: -2.8 },
      { month: 12, winRate: 78, avgReturn: 1.8, medianReturn: 1.6, maxGain: 6.5, maxLoss: -3.1 },
    ],
    windows: [
      {
        title: "Best Six Months / Golden Seasonal Window",
        bias: "bullish",
        startMonth: 10,
        startDay: 28,
        endMonth: 4,
        endDay: 30,
        winRate: 80.0,
        avgReturn: 7.8,
        description: "Historically the strongest half of the year for S&P 500 ('Sell in May and Go Away' counterpart).",
      },
      {
        title: "Late Summer Seasonal Caution Window",
        bias: "bearish",
        startMonth: 8,
        startDay: 1,
        endMonth: 9,
        endDay: 30,
        winRate: 38.0,
        avgReturn: -1.4,
        description: "Historically low volume and volatile period leading into September lows.",
      },
      {
        title: "Santa Claus & Year-End Rally Window",
        bias: "bullish",
        startMonth: 12,
        startDay: 15,
        endMonth: 1,
        endDay: 5,
        winRate: 76.0,
        avgReturn: 2.1,
        description: "Institutional window dressing and low liquidity drive strong year-end upside.",
      },
    ],
  },
  {
    ticker: "XLK",
    name: "Technology Select Sector SPDR ETF",
    category: "Sectors",
    sector: "Technology",
    description: "Tracks top US technology leaders including Apple, Microsoft, NVIDIA, and Broadcom.",
    equityclockUrl: "https://equityclock.com/charts/technology-select-sector-spdr-etf-xlk-seasonal-chart/",
    lastPrice: 215.30,
    dayChangePct: 0.85,
    rsi14: 62.1,
    aboveSma50: true,
    aboveSma200: true,
    confluenceScore: 88,
    monthly: [
      { month: 1, winRate: 65, avgReturn: 2.1, medianReturn: 1.9, maxGain: 8.5, maxLoss: -5.2 },
      { month: 2, winRate: 52, avgReturn: 0.2, medianReturn: 0.1, maxGain: 6.0, maxLoss: -6.8 },
      { month: 3, winRate: 68, avgReturn: 1.8, medianReturn: 1.6, maxGain: 7.8, maxLoss: -4.5 },
      { month: 4, winRate: 72, avgReturn: 2.3, medianReturn: 2.1, maxGain: 9.0, maxLoss: -3.8 },
      { month: 5, winRate: 60, avgReturn: 0.8, medianReturn: 0.6, maxGain: 6.2, maxLoss: -5.1 },
      { month: 6, winRate: 65, avgReturn: 1.5, medianReturn: 1.4, maxGain: 7.1, maxLoss: -4.2 },
      { month: 7, winRate: 76, avgReturn: 2.8, medianReturn: 2.6, maxGain: 10.2, maxLoss: -3.0 },
      { month: 8, winRate: 50, avgReturn: -0.1, medianReturn: 0.0, maxGain: 5.3, maxLoss: -7.0 },
      { month: 9, winRate: 38, avgReturn: -1.8, medianReturn: -1.5, maxGain: 4.1, maxLoss: -9.8 },
      { month: 10, winRate: 70, avgReturn: 2.2, medianReturn: 2.0, maxGain: 8.9, maxLoss: -6.2 },
      { month: 11, winRate: 80, avgReturn: 3.4, medianReturn: 3.1, maxGain: 11.5, maxLoss: -2.5 },
      { month: 12, winRate: 72, avgReturn: 2.0, medianReturn: 1.8, maxGain: 7.4, maxLoss: -3.6 },
    ],
    windows: [
      {
        title: "Q4 Tech Acceleration & Holiday Demand",
        bias: "bullish",
        startMonth: 10,
        startDay: 10,
        endMonth: 1,
        endDay: 15,
        winRate: 82.0,
        avgReturn: 8.5,
        description: "Institutional rebalancing and holiday consumer electronics tailwinds.",
      },
      {
        title: "Summer Tech Earnings Rally",
        bias: "bullish",
        startMonth: 6,
        startDay: 20,
        endMonth: 7,
        endDay: 30,
        winRate: 78.0,
        avgReturn: 4.1,
        description: "Q2 earnings season historically sees strong tech upside momentum.",
      },
      {
        title: "September Tech Drawdown Window",
        bias: "bearish",
        startMonth: 9,
        startDay: 1,
        endMonth: 9,
        endDay: 30,
        winRate: 35.0,
        avgReturn: -2.1,
        description: "Worst month historically for semiconductor and software leadership.",
      },
    ],
  },
  {
    ticker: "XLE",
    name: "Energy Select Sector SPDR ETF",
    category: "Sectors",
    sector: "Energy",
    description: "Tracks major US oil & gas exploration, production, and refining companies like Exxon & Chevron.",
    equityclockUrl: "https://equityclock.com/charts/energy-select-sector-spdr-etf-xle-seasonal-chart/",
    lastPrice: 91.40,
    dayChangePct: -0.35,
    rsi14: 51.0,
    aboveSma50: true,
    aboveSma200: true,
    confluenceScore: 78,
    monthly: [
      { month: 1, winRate: 58, avgReturn: 1.2, medianReturn: 1.0, maxGain: 9.8, maxLoss: -8.1 },
      { month: 2, winRate: 70, avgReturn: 2.8, medianReturn: 2.5, maxGain: 10.5, maxLoss: -4.2 },
      { month: 3, winRate: 72, avgReturn: 3.1, medianReturn: 2.9, maxGain: 11.2, maxLoss: -5.0 },
      { month: 4, winRate: 75, avgReturn: 2.9, medianReturn: 2.7, maxGain: 9.8, maxLoss: -3.9 },
      { month: 5, winRate: 58, avgReturn: 1.1, medianReturn: 0.9, maxGain: 7.5, maxLoss: -6.4 },
      { month: 6, winRate: 42, avgReturn: -1.5, medianReturn: -1.2, maxGain: 5.2, maxLoss: -8.8 },
      { month: 7, winRate: 55, avgReturn: 0.8, medianReturn: 0.6, maxGain: 6.8, maxLoss: -7.1 },
      { month: 8, winRate: 45, avgReturn: -1.2, medianReturn: -0.9, maxGain: 5.1, maxLoss: -9.0 },
      { month: 9, winRate: 38, avgReturn: -2.1, medianReturn: -1.8, maxGain: 4.8, maxLoss: -11.2 },
      { month: 10, winRate: 58, avgReturn: 1.4, medianReturn: 1.1, maxGain: 8.2, maxLoss: -7.5 },
      { month: 11, winRate: 62, avgReturn: 1.8, medianReturn: 1.5, maxGain: 8.9, maxLoss: -6.0 },
      { month: 12, winRate: 52, avgReturn: 0.5, medianReturn: 0.3, maxGain: 6.1, maxLoss: -6.8 },
    ],
    windows: [
      {
        title: "Spring Refinery Turnaround & Driving Season Build",
        bias: "bullish",
        startMonth: 2,
        startDay: 25,
        endMonth: 5,
        endDay: 25,
        winRate: 78.0,
        avgReturn: 7.5,
        description: "Refinery maintenance and anticipated summer fuel consumption drive energy stocks higher.",
      },
      {
        title: "Late Summer Off-Peak Liquidation Window",
        bias: "bearish",
        startMonth: 6,
        startDay: 1,
        endMonth: 9,
        endDay: 30,
        winRate: 40.0,
        avgReturn: -3.8,
        description: "Post-driving season inventory accumulation and global demand softening.",
      },
    ],
  },
  {
    ticker: "GLD",
    name: "SPDR Gold Shares ETF / Spot Gold",
    category: "Commodities",
    sector: "Precious Metals",
    description: "Tracks the physical price performance of bullion Gold.",
    equityclockUrl: "https://equityclock.com/charts/spdr-gold-shares-gld-seasonal-chart/",
    lastPrice: 228.80,
    dayChangePct: 1.12,
    rsi14: 66.4,
    aboveSma50: true,
    aboveSma200: true,
    confluenceScore: 92,
    monthly: [
      { month: 1, winRate: 75, avgReturn: 3.2, medianReturn: 3.0, maxGain: 11.4, maxLoss: -3.8 },
      { month: 2, winRate: 68, avgReturn: 1.9, medianReturn: 1.7, maxGain: 8.2, maxLoss: -4.1 },
      { month: 3, winRate: 42, avgReturn: -1.2, medianReturn: -0.9, maxGain: 5.0, maxLoss: -6.2 },
      { month: 4, winRate: 55, avgReturn: 0.8, medianReturn: 0.6, maxGain: 6.1, maxLoss: -4.9 },
      { month: 5, winRate: 48, avgReturn: -0.5, medianReturn: -0.2, maxGain: 5.3, maxLoss: -5.8 },
      { month: 6, winRate: 45, avgReturn: -0.8, medianReturn: -0.5, maxGain: 4.8, maxLoss: -5.2 },
      { month: 7, winRate: 62, avgReturn: 1.5, medianReturn: 1.3, maxGain: 7.2, maxLoss: -4.0 },
      { month: 8, winRate: 65, avgReturn: 2.1, medianReturn: 1.9, maxGain: 9.0, maxLoss: -4.5 },
      { month: 9, winRate: 52, avgReturn: 0.5, medianReturn: 0.3, maxGain: 6.4, maxLoss: -6.0 },
      { month: 10, winRate: 48, avgReturn: -0.4, medianReturn: -0.1, maxGain: 5.1, maxLoss: -5.5 },
      { month: 11, winRate: 50, avgReturn: 0.1, medianReturn: 0.0, maxGain: 5.8, maxLoss: -5.9 },
      { month: 12, winRate: 65, avgReturn: 1.8, medianReturn: 1.5, maxGain: 7.6, maxLoss: -3.2 },
    ],
    windows: [
      {
        title: "Q1 Gold Rally Window (Global Demand & Holidays)",
        bias: "bullish",
        startMonth: 12,
        startDay: 20,
        endMonth: 2,
        endDay: 24,
        winRate: 81.0,
        avgReturn: 6.2,
        description: "Indian wedding season, Chinese New Year physical gold purchases, and portfolio hedging.",
      },
      {
        title: "Late Summer Physical Accumulation Phase",
        bias: "bullish",
        startMonth: 7,
        startDay: 10,
        endMonth: 9,
        endDay: 5,
        winRate: 70.0,
        avgReturn: 3.5,
        description: "Jewelry fabrication stock up ahead of autumn festivals.",
      },
      {
        title: "Spring Gold Consolidation Window",
        bias: "bearish",
        startMonth: 3,
        startDay: 1,
        endMonth: 3,
        endDay: 31,
        winRate: 42.0,
        avgReturn: -1.2,
        description: "Profit taking following Q1 strength and rising Q1 yields.",
      },
    ],
  },
  {
    ticker: "CL=F",
    name: "Crude Oil Futures (WTI)",
    category: "Commodities",
    sector: "Energy",
    description: "West Texas Intermediate benchmark crude oil futures contract.",
    equityclockUrl: "https://equityclock.com/charts/crude-oil-seasonal-chart/",
    lastPrice: 82.50,
    dayChangePct: -0.60,
    rsi14: 54.2,
    aboveSma50: true,
    aboveSma200: true,
    confluenceScore: 81,
    monthly: [
      { month: 1, winRate: 55, avgReturn: 1.0, medianReturn: 0.8, maxGain: 12.5, maxLoss: -9.0 },
      { month: 2, winRate: 72, avgReturn: 3.5, medianReturn: 3.2, maxGain: 14.2, maxLoss: -6.1 },
      { month: 3, winRate: 75, avgReturn: 3.8, medianReturn: 3.5, maxGain: 15.0, maxLoss: -5.8 },
      { month: 4, winRate: 78, avgReturn: 4.2, medianReturn: 3.9, maxGain: 16.1, maxLoss: -4.2 },
      { month: 5, winRate: 65, avgReturn: 2.1, medianReturn: 1.8, maxGain: 11.0, maxLoss: -7.0 },
      { month: 6, winRate: 60, avgReturn: 1.8, medianReturn: 1.5, maxGain: 9.8, maxLoss: -7.5 },
      { month: 7, winRate: 48, avgReturn: -0.8, medianReturn: -0.5, maxGain: 8.1, maxLoss: -10.2 },
      { month: 8, winRate: 42, avgReturn: -1.5, medianReturn: -1.2, maxGain: 7.0, maxLoss: -11.5 },
      { month: 9, winRate: 35, avgReturn: -2.8, medianReturn: -2.4, maxGain: 6.2, maxLoss: -14.0 },
      { month: 10, winRate: 42, avgReturn: -1.8, medianReturn: -1.5, maxGain: 7.5, maxLoss: -12.1 },
      { month: 11, winRate: 38, avgReturn: -2.1, medianReturn: -1.8, maxGain: 6.8, maxLoss: -13.0 },
      { month: 12, winRate: 52, avgReturn: 0.8, medianReturn: 0.5, maxGain: 8.9, maxLoss: -8.5 },
    ],
    windows: [
      {
        title: "Spring Crude Surge (Driving Season + Maintenance)",
        bias: "bullish",
        startMonth: 2,
        startDay: 10,
        endMonth: 6,
        endDay: 30,
        winRate: 82.0,
        avgReturn: 12.8,
        description: "Refineries ramp up processing ahead of summer driving, boosting raw crude demand.",
      },
      {
        title: "Autumn Crude Inventory Drawdown & Slump",
        bias: "bearish",
        startMonth: 8,
        startDay: 1,
        endMonth: 11,
        endDay: 20,
        winRate: 32.0,
        avgReturn: -7.2,
        description: "End of US summer driving season combined with autumn refinery maintenance.",
      },
    ],
  },
  {
    ticker: "BTC",
    name: "Bitcoin Spot (USD)",
    category: "Crypto",
    sector: "Digital Assets",
    description: "Leading decentralized digital currency by market capitalization.",
    equityclockUrl: "https://equityclock.com/charts/bitcoin-seasonal-chart/",
    lastPrice: 68450.00,
    dayChangePct: 2.30,
    rsi14: 61.5,
    aboveSma50: true,
    aboveSma200: true,
    confluenceScore: 89,
    monthly: [
      { month: 1, winRate: 58, avgReturn: 2.5, medianReturn: 2.1, maxGain: 31.0, maxLoss: -20.0 },
      { month: 2, winRate: 70, avgReturn: 8.2, medianReturn: 7.5, maxGain: 42.0, maxLoss: -15.0 },
      { month: 3, winRate: 60, avgReturn: 3.1, medianReturn: 2.8, maxGain: 28.0, maxLoss: -18.0 },
      { month: 4, winRate: 68, avgReturn: 6.5, medianReturn: 5.8, maxGain: 35.0, maxLoss: -12.0 },
      { month: 5, winRate: 42, avgReturn: -2.1, medianReturn: -1.8, maxGain: 22.0, maxLoss: -35.0 },
      { month: 6, winRate: 35, avgReturn: -4.2, medianReturn: -3.8, maxGain: 18.0, maxLoss: -38.0 },
      { month: 7, winRate: 62, avgReturn: 4.1, medianReturn: 3.5, maxGain: 25.0, maxLoss: -16.0 },
      { month: 8, winRate: 38, avgReturn: -3.5, medianReturn: -3.0, maxGain: 15.0, maxLoss: -22.0 },
      { month: 9, winRate: 30, avgReturn: -4.8, medianReturn: -4.2, maxGain: 12.0, maxLoss: -25.0 },
      { month: 10, winRate: 82, avgReturn: 12.4, medianReturn: 11.2, maxGain: 48.0, maxLoss: -10.0 },
      { month: 11, winRate: 78, avgReturn: 14.2, medianReturn: 12.8, maxGain: 55.0, maxLoss: -18.0 },
      { month: 12, winRate: 62, avgReturn: 5.1, medianReturn: 4.5, maxGain: 30.0, maxLoss: -15.0 },
    ],
    windows: [
      {
        title: "Uptober & Q4 Crypto Bull Season",
        bias: "bullish",
        startMonth: 10,
        startDay: 1,
        endMonth: 12,
        endDay: 20,
        winRate: 85.0,
        avgReturn: 28.5,
        description: "Historically Bitcoin's highest performing quarter with immense institutional momentum.",
      },
      {
        title: "Late Spring / Summer Crypto Lull",
        bias: "bearish",
        startMonth: 5,
        startDay: 1,
        endMonth: 9,
        endDay: 30,
        winRate: 34.0,
        avgReturn: -9.8,
        description: "Low liquidity summer months often experience chop and deep retracements.",
      },
    ],
  },
  {
    ticker: "TLT",
    name: "iShares 20+ Year Treasury Bond ETF",
    category: "Bonds",
    sector: "US Fixed Income",
    description: "Tracks long-term US Treasury bonds, highly sensitive to interest rate expectations.",
    equityclockUrl: "https://equityclock.com/charts/ishares-20-year-treasury-bond-etf-tlt-seasonal-chart/",
    lastPrice: 94.20,
    dayChangePct: 0.15,
    rsi14: 48.0,
    aboveSma50: false,
    aboveSma200: false,
    confluenceScore: 55,
    monthly: [
      { month: 1, winRate: 48, avgReturn: -0.2, medianReturn: 0.0, maxGain: 5.2, maxLoss: -5.8 },
      { month: 2, winRate: 52, avgReturn: 0.3, medianReturn: 0.2, maxGain: 4.8, maxLoss: -4.9 },
      { month: 3, winRate: 50, avgReturn: 0.1, medianReturn: 0.0, maxGain: 5.0, maxLoss: -5.1 },
      { month: 4, winRate: 45, avgReturn: -0.4, medianReturn: -0.2, maxGain: 4.2, maxLoss: -6.0 },
      { month: 5, winRate: 65, avgReturn: 1.5, medianReturn: 1.2, maxGain: 7.1, maxLoss: -3.8 },
      { month: 6, winRate: 62, avgReturn: 1.2, medianReturn: 1.0, maxGain: 6.5, maxLoss: -3.5 },
      { month: 7, winRate: 68, avgReturn: 1.8, medianReturn: 1.6, maxGain: 7.8, maxLoss: -3.0 },
      { month: 8, winRate: 72, avgReturn: 2.2, medianReturn: 2.0, maxGain: 8.4, maxLoss: -2.8 },
      { month: 9, winRate: 58, avgReturn: 0.6, medianReturn: 0.4, maxGain: 5.9, maxLoss: -4.8 },
      { month: 10, winRate: 42, avgReturn: -0.8, medianReturn: -0.5, maxGain: 4.5, maxLoss: -6.8 },
      { month: 11, winRate: 55, avgReturn: 0.5, medianReturn: 0.3, maxGain: 5.8, maxLoss: -4.2 },
      { month: 12, winRate: 58, avgReturn: 0.8, medianReturn: 0.6, maxGain: 6.0, maxLoss: -3.9 },
    ],
    windows: [
      {
        title: "Summer Flight-to-Safety Window",
        bias: "bullish",
        startMonth: 5,
        startDay: 1,
        endMonth: 8,
        endDay: 31,
        winRate: 74.0,
        avgReturn: 5.2,
        description: "Bonds perform strongly as equities face summer volatility and economic slow period.",
      },
      {
        title: "Autumn Bond Yield Surge / TLT Weakness",
        bias: "bearish",
        startMonth: 10,
        startDay: 1,
        endMonth: 10,
        endDay: 31,
        winRate: 40.0,
        avgReturn: -0.8,
        description: "Yields historically rise as stock market bottoming draws capital into risk assets.",
      },
    ],
  },
  {
    ticker: "EURUSD",
    name: "EUR / USD Spot Exchange Rate",
    category: "Forex",
    sector: "Currencies",
    description: "Euro vs United States Dollar currency pair.",
    equityclockUrl: "https://equityclock.com/charts/eurusd-seasonal-chart/",
    lastPrice: 1.0850,
    dayChangePct: -0.12,
    rsi14: 49.5,
    aboveSma50: true,
    aboveSma200: false,
    confluenceScore: 68,
    monthly: [
      { month: 1, winRate: 48, avgReturn: -0.3, medianReturn: -0.1, maxGain: 3.5, maxLoss: -4.2 },
      { month: 2, winRate: 42, avgReturn: -0.5, medianReturn: -0.3, maxGain: 3.1, maxLoss: -4.8 },
      { month: 3, winRate: 52, avgReturn: 0.1, medianReturn: 0.0, maxGain: 3.8, maxLoss: -3.9 },
      { month: 4, winRate: 68, avgReturn: 1.2, medianReturn: 1.0, maxGain: 4.9, maxLoss: -2.5 },
      { month: 5, winRate: 45, avgReturn: -0.4, medianReturn: -0.2, maxGain: 3.2, maxLoss: -4.5 },
      { month: 6, winRate: 50, avgReturn: 0.0, medianReturn: 0.0, maxGain: 3.5, maxLoss: -3.6 },
      { month: 7, winRate: 58, avgReturn: 0.8, medianReturn: 0.6, maxGain: 4.2, maxLoss: -3.0 },
      { month: 8, winRate: 48, avgReturn: -0.2, medianReturn: -0.1, maxGain: 3.0, maxLoss: -3.8 },
      { month: 9, winRate: 40, avgReturn: -0.9, medianReturn: -0.7, maxGain: 2.8, maxLoss: -5.1 },
      { month: 10, winRate: 52, avgReturn: 0.2, medianReturn: 0.1, maxGain: 3.4, maxLoss: -3.7 },
      { month: 11, winRate: 55, avgReturn: 0.4, medianReturn: 0.3, maxGain: 4.0, maxLoss: -3.5 },
      { month: 12, winRate: 72, avgReturn: 1.5, medianReturn: 1.3, maxGain: 5.1, maxLoss: -2.1 },
    ],
    windows: [
      {
        title: "December USD Weakness & Euro Rally",
        bias: "bullish",
        startMonth: 12,
        startDay: 1,
        endMonth: 12,
        endDay: 31,
        winRate: 75.0,
        avgReturn: 1.5,
        description: "Year-end USD corporate repatriation and central bank liquidity operations.",
      },
      {
        title: "April Spring Euro Window",
        bias: "bullish",
        startMonth: 4,
        startDay: 1,
        endMonth: 4,
        endDay: 30,
        winRate: 70.0,
        avgReturn: 1.2,
        description: "European spring trade balances and dividend repatriation season.",
      },
    ],
  },
  {
    ticker: "XLF",
    name: "Financial Select Sector SPDR ETF",
    category: "Sectors",
    sector: "Financials",
    description: "Tracks US banking, insurance, investment banking, and capital markets giants.",
    equityclockUrl: "https://equityclock.com/charts/financial-select-sector-spdr-etf-xlf-seasonal-chart/",
    lastPrice: 42.15,
    dayChangePct: 0.38,
    rsi14: 56.4,
    aboveSma50: true,
    aboveSma200: true,
    confluenceScore: 82,
    monthly: [
      { month: 1, winRate: 55, avgReturn: 0.5, medianReturn: 0.3, maxGain: 7.2, maxLoss: -6.5 },
      { month: 2, winRate: 58, avgReturn: 0.8, medianReturn: 0.6, maxGain: 6.5, maxLoss: -5.8 },
      { month: 3, winRate: 62, avgReturn: 1.2, medianReturn: 1.0, maxGain: 7.0, maxLoss: -5.0 },
      { month: 4, winRate: 70, avgReturn: 2.1, medianReturn: 1.9, maxGain: 8.5, maxLoss: -3.8 },
      { month: 5, winRate: 52, avgReturn: 0.1, medianReturn: 0.0, maxGain: 5.4, maxLoss: -6.1 },
      { month: 6, winRate: 48, avgReturn: -0.2, medianReturn: -0.1, maxGain: 5.1, maxLoss: -5.9 },
      { month: 7, winRate: 65, avgReturn: 1.7, medianReturn: 1.5, maxGain: 7.8, maxLoss: -4.2 },
      { month: 8, winRate: 45, avgReturn: -0.5, medianReturn: -0.3, maxGain: 4.8, maxLoss: -7.0 },
      { month: 9, winRate: 40, avgReturn: -1.3, medianReturn: -1.0, maxGain: 4.1, maxLoss: -8.5 },
      { month: 10, winRate: 64, avgReturn: 1.5, medianReturn: 1.3, maxGain: 8.0, maxLoss: -5.5 },
      { month: 11, winRate: 76, avgReturn: 2.8, medianReturn: 2.5, maxGain: 9.2, maxLoss: -3.0 },
      { month: 12, winRate: 68, avgReturn: 1.4, medianReturn: 1.2, maxGain: 6.4, maxLoss: -3.8 },
    ],
    windows: [
      {
        title: "Q4 Financials Earnings & Year-End Rally",
        bias: "bullish",
        startMonth: 10,
        startDay: 15,
        endMonth: 12,
        endDay: 31,
        winRate: 78.0,
        avgReturn: 4.2,
        description: "Strong bank earnings performance and capital allocation planning.",
      },
      {
        title: "Spring Financials Accumulation",
        bias: "bullish",
        startMonth: 3,
        startDay: 15,
        endMonth: 4,
        endDay: 30,
        winRate: 72.0,
        avgReturn: 2.8,
        description: "Q1 bank reporting and dividend announcements boost banking stocks.",
      },
    ],
  },
  {
    ticker: "XLV",
    name: "Health Care Select Sector SPDR ETF",
    category: "Sectors",
    sector: "Healthcare",
    description: "Tracks pharmaceutical, medical device, and healthcare provider leaders.",
    equityclockUrl: "https://equityclock.com/charts/health-care-select-sector-spdr-etf-xlv-seasonal-chart/",
    lastPrice: 144.60,
    dayChangePct: 0.18,
    rsi14: 52.8,
    aboveSma50: true,
    aboveSma200: true,
    confluenceScore: 76,
    monthly: [
      { month: 1, winRate: 58, avgReturn: 0.8, medianReturn: 0.6, maxGain: 5.8, maxLoss: -4.5 },
      { month: 2, winRate: 60, avgReturn: 0.9, medianReturn: 0.7, maxGain: 5.5, maxLoss: -4.2 },
      { month: 3, winRate: 62, avgReturn: 1.1, medianReturn: 0.9, maxGain: 6.1, maxLoss: -4.0 },
      { month: 4, winRate: 70, avgReturn: 1.8, medianReturn: 1.6, maxGain: 7.2, maxLoss: -3.2 },
      { month: 5, winRate: 55, avgReturn: 0.3, medianReturn: 0.2, maxGain: 4.9, maxLoss: -5.0 },
      { month: 6, winRate: 65, avgReturn: 1.4, medianReturn: 1.2, maxGain: 6.0, maxLoss: -3.5 },
      { month: 7, winRate: 68, avgReturn: 1.6, medianReturn: 1.4, maxGain: 6.8, maxLoss: -3.1 },
      { month: 8, winRate: 58, avgReturn: 0.4, medianReturn: 0.3, maxGain: 5.0, maxLoss: -4.8 },
      { month: 9, winRate: 48, avgReturn: -0.4, medianReturn: -0.2, maxGain: 4.2, maxLoss: -5.9 },
      { month: 10, winRate: 58, avgReturn: 0.9, medianReturn: 0.7, maxGain: 6.2, maxLoss: -4.9 },
      { month: 11, winRate: 65, avgReturn: 1.5, medianReturn: 1.3, maxGain: 6.9, maxLoss: -3.4 },
      { month: 12, winRate: 72, avgReturn: 1.9, medianReturn: 1.7, maxGain: 6.5, maxLoss: -2.8 },
    ],
    windows: [
      {
        title: "Defensive Health Care Defensive Outperformance",
        bias: "bullish",
        startMonth: 6,
        startDay: 1,
        endMonth: 7,
        endDay: 31,
        winRate: 71.0,
        avgReturn: 3.0,
        description: "Investors tilt defensive into summer medical conferences and Q2 earnings stability.",
      },
    ],
  },
];

export const RECENT_UPDATES = [
  {
    ticker: "SPX",
    title: "S&P 500 Enters Strongest Historical Window of the Year",
    snippet: "Historical data over 50 years reveals that the period between late October and April generates over 80% of annual benchmark gains.",
    bias: "bullish",
    publishDate: "2025-02-15",
    sourceUrl: "https://equityclock.com/",
  },
  {
    ticker: "CL=F",
    title: "Crude Oil Seasonal Strength Begins Ahead of Refinement Season",
    snippet: "Refiners ramp up crude purchasing starting mid-February in preparation for the upcoming US summer driving demand surge.",
    bias: "bullish",
    publishDate: "2025-02-12",
    sourceUrl: "https://equityclock.com/",
  },
  {
    ticker: "XLK",
    title: "Tech Sector Seasonality Confluence Signals Strong Risk-On Setup",
    snippet: "XLK RSI-14 combined with historical April win rate (72%) indicates high-probability swing setup.",
    bias: "bullish",
    publishDate: "2025-02-10",
    sourceUrl: "https://equityclock.com/",
  },
  {
    ticker: "GLD",
    title: "Gold Q1 Peak Window Approaching Final Targets",
    snippet: "Gold physical demand peaks during Q1 seasonal window. Watch for potential March consolidation period.",
    bias: "neutral",
    publishDate: "2025-02-08",
    sourceUrl: "https://equityclock.com/",
  },
  {
    ticker: "TLT",
    title: "Treasuries Preparing for Seasonal Summer Flight-to-Quality",
    snippet: "Long duration bonds historically find support starting in May as equity momentum cools down.",
    bias: "bullish",
    publishDate: "2025-02-05",
    sourceUrl: "https://equityclock.com/",
  },
];

export async function ensureSeedData() {
  try {
    const existing = await db.select().from(assets).limit(1);
    if (existing.length > 0) {
      return { success: true, message: "Database already seeded." };
    }

    for (const item of SEED_ASSETS) {
      const [insertedAsset] = await db.insert(assets).values({
        ticker: item.ticker,
        name: item.name,
        category: item.category,
        sector: item.sector,
        description: item.description,
        equityclockUrl: item.equityclockUrl,
      }).returning();

      for (const m of item.monthly) {
        await db.insert(monthlySeasonality).values({
          assetId: insertedAsset.id,
          month: m.month,
          winRate: m.winRate,
          avgReturn: m.avgReturn,
          medianReturn: m.medianReturn,
          maxGain: m.maxGain,
          maxLoss: m.maxLoss,
          sampleYears: 20,
        });
      }

      for (const w of item.windows) {
        await db.insert(seasonalWindows).values({
          assetId: insertedAsset.id,
          title: w.title,
          bias: w.bias,
          startMonth: w.startMonth,
          startDay: w.startDay,
          endMonth: w.endMonth,
          endDay: w.endDay,
          winRate: w.winRate,
          avgReturn: w.avgReturn,
          description: w.description,
        });
      }

      await db.insert(assetTechnicals).values({
        assetId: insertedAsset.id,
        lastPrice: item.lastPrice,
        dayChangePct: item.dayChangePct,
        rsi14: item.rsi14,
        aboveSma50: item.aboveSma50,
        aboveSma200: item.aboveSma200,
        confluenceScore: item.confluenceScore,
      });
    }

    for (const update of RECENT_UPDATES) {
      await db.insert(seasonalUpdates).values(update);
    }

    return { success: true, message: `Seeded ${SEED_ASSETS.length} assets successfully.` };
  } catch (err: any) {
    console.error("Error in ensureSeedData:", err);
    return { success: false, error: err.message };
  }
}
